<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>line_orchestrator</name>
  <version>0.1.0</version>
  <description>Orquestador de la linea y nodo de prueba de estacion.</description>
  <maintainer email="santiagomach2@hotmail.com">Santiago Machado</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>line_interfaces</depend>
  <depend>geometry_msgs</depend>
  <depend>python3-yaml</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
